name: Core Edu - Auth Part

on:
  push:
    branches: [ main ]
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Auth
      uses: docker/build-push-action@v5
      with:
        context: ./auth
        push: true
        tags: ghcr.io/sverdlovsky/core-edu-auth:latest
        cache-from: type=registry,ref=ghcr.io/sverdlovsky/core-edu-auth:latest
        cache-to: type=registry,ref=ghcr.io/sverdlovsky/core-edu-auth:latest,mode=max
        platforms: linux/amd64

